version: "3.1"
services:
  nginx:
    container_name: nginx-server
    image: nginx:stable 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./assets:/usr/share/nginx/html
      - ./ssl/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/proyecto2st0263eafit.tk/fullchain.pem:/etc/letsencrypt/live/proyecto2st0263eafit.tk/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/proyecto2st0263eafit.tk/privkey.pem:/etc/letsencrypt/live/proyecto2st0263eafit.tk/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nodeapp
  nodeapp:
    container_name: nodeapp
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo-server      
  mongo-server:
    container_name: mongo-server
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
    - "27017:27017"
